/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    investors: InvestorAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'fact-sheets': FactSheet;
    products: Product;
    metrics: Metric;
    investors: Investor;
    users: User;
    'audit-log': AuditLog;
    media: Media;
    'login-challenges': LoginChallenge;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'fact-sheets': FactSheetsSelect<false> | FactSheetsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    metrics: MetricsSelect<false> | MetricsSelect<true>;
    investors: InvestorsSelect<false> | InvestorsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'login-challenges': LoginChallengesSelect<false> | LoginChallengesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Investor | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface InvestorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Draft, submit for review, and compliance publishes. A published sheet never changes; fix a mistake with a new sheet for the same month.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fact-sheets".
 */
export interface FactSheet {
  id: number;
  title?: string | null;
  product: number | Product;
  /**
   * The last day the returns cover, e.g. 31 August 2026.
   */
  asOf: string;
  /**
   * Draft, then waiting for approval. Compliance publishes.
   */
  status: 'draft' | 'in_review' | 'published' | 'superseded';
  /**
   * One row per period. Leave a value empty when the period has not run; the site prints N/A.
   */
  returns?:
    | {
        period: '1M' | '3M' | '6M' | '1Y' | '2Y' | '3Y' | '5Y' | 'SI';
        ours?: number | null;
        benchmark?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * What Rs. 1 Mn invested at inception is worth on the as-of date, in Rs. Mn. Leave empty if the deck does not give it.
   */
  wealth?: {
    ours?: number | null;
    benchmark?: number | null;
  };
  sectors?:
    | {
        name: string;
        weight: number;
        id?: string | null;
      }[]
    | null;
  pdf?: (number | null) | Media;
  /**
   * Only when replacing a sheet already published for the same month: what was wrong.
   */
  correctionReason?: string | null;
  submittedBy?: (number | null) | User;
  submittedAt?: string | null;
  approvedBy?: (number | null) | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Used in links and code, e.g. moneybee-pms. Do not change once live.
   */
  slug: string;
  kind: 'pms' | 'aif';
  /**
   * Exactly as the returns table prints it, e.g. S&P BSE 500 TRI.
   */
  benchmark: string;
  inception: string;
  /**
   * SEBI registration number.
   */
  registration?: string | null;
  /**
   * Off keeps this product's returns off the public site. AIF returns stay off until compliance clears them (plan §11).
   */
  showPerformancePublicly?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the file shows, for screen readers.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admin can do everything. Compliance approves anything that shows numbers. Only an admin can change roles.
   */
  roles: ('admin' | 'editor' | 'compliance' | 'sales' | 'hr' | 'operations' | 'integration')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metrics".
 */
export interface Metric {
  id: number;
  label: string;
  /**
   * The name code uses, e.g. founderYears. Do not change once live.
   */
  key: string;
  value: number;
  unit?: ('none' | 'percent' | 'years' | 'crore' | 'stocks') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investors".
 */
export interface Investor {
  id: number;
  name: string;
  phone?: string | null;
  /**
   * Back-office client codes. Statement files named with these codes go to this investor.
   */
  clientCodes?: string[] | null;
  status: 'active' | 'disabled';
  trustedDevices?:
    | {
        hash: string;
        lastUsedAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'investors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  actor?: (number | null) | User;
  action: string;
  collectionSlug: string;
  docId: string;
  summary?: string | null;
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-challenges".
 */
export interface LoginChallenge {
  id: number;
  investor: number | Investor;
  nonceHash: string;
  codeHash: string;
  sealedToken: string;
  sessionExpires: string;
  expiresAt: string;
  attempts: number;
  consumedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'fact-sheets';
        value: number | FactSheet;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'metrics';
        value: number | Metric;
      } | null)
    | ({
        relationTo: 'investors';
        value: number | Investor;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'login-challenges';
        value: number | LoginChallenge;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'investors';
        value: number | Investor;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'investors';
        value: number | Investor;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fact-sheets_select".
 */
export interface FactSheetsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  asOf?: T;
  status?: T;
  returns?:
    | T
    | {
        period?: T;
        ours?: T;
        benchmark?: T;
        id?: T;
      };
  wealth?:
    | T
    | {
        ours?: T;
        benchmark?: T;
      };
  sectors?:
    | T
    | {
        name?: T;
        weight?: T;
        id?: T;
      };
  pdf?: T;
  correctionReason?: T;
  submittedBy?: T;
  submittedAt?: T;
  approvedBy?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  benchmark?: T;
  inception?: T;
  registration?: T;
  showPerformancePublicly?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metrics_select".
 */
export interface MetricsSelect<T extends boolean = true> {
  label?: T;
  key?: T;
  value?: T;
  unit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investors_select".
 */
export interface InvestorsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  clientCodes?: T;
  status?: T;
  trustedDevices?:
    | T
    | {
        hash?: T;
        lastUsedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  collectionSlug?: T;
  docId?: T;
  summary?: T;
  changes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-challenges_select".
 */
export interface LoginChallengesSelect<T extends boolean = true> {
  investor?: T;
  nonceHash?: T;
  codeHash?: T;
  sealedToken?: T;
  sessionExpires?: T;
  expiresAt?: T;
  attempts?: T;
  consumedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}